.TH PAULSTRETCH "1" "Jan 2012"
.SH NOM
paulstretch \- Étirement (Time\-Stretch) extrême de la longeur d'un son.
.SH SYNOPSIS
.B paulstretch
.SH DESCRIPTION
C'est un programme pour allonger l'audio. 
Il est conçu uniquement pour un étirement extrême du son d'un matériel audio 
(genre 50x) et pour l'application d'effets en "lissant le spectre" des sons. 
Il peut transformer tout son/musique en une texture.
.PP
Il produit un étirement extrême du son de haute-qualité. Alors que la plupart 
des logiciels d'étirement sonnent mal lorsque l'on essaie d'étirer 
énormément les sons, celui-ci est optimisé pour une élongation extrême.
.PP
La quantité d'étirement est illimitée. 
Vous pouvez lire le son étiré en temps-réel (ceci inclue la possibilité de 
"geler" le son) ou vous pouvez effectuer un rendu du son en entier, ou 
seulement d'une partie, vers des fichiers audio.
.PP
.SH OPTION
.PP
Vous pouvez lancer paulstretch depuis la ligne de commande avec un fichier
audio choisi avec :
.HP
\fB\paulstretch\fR <nomdefichieraudio> \- démarre en chargeant nomdefichieraudio
.SH "VOIR ÉGALEMENT"
Un guide rapide est disponible sur 
<http://hypermammut.sourceforge.net/paulstretch/> (en anglais).
.SH "AUTEUR"
paulstretch a été écrit par Nasca Octavian PAUL.
.PP
Cette page de manuel a été écrite par Robin Gareus <robin@gareus.org> 
pour le projet Debian (et peut être utilisée par d'autres). Elle a été traduite 
en français par Olivier Humbert pour le projet LibraZiK (et peut être utilisée 
par d'autres).
